sudo: false
language: python

python:
  - "2.7"

install:
    - pip install pep8 tox

before_script:
    - "pep8 --ignore=E123,E402,E501,E701 ./bin ./zask ./tests"

script:
    - make test

branches:
  #only:
  #  - master

notifications:
  slack:
    rooms:
      - juwai:BnihlKlSqagkR1FS7agVecXg
    on_success: never
    on_failure: always
